"""
personalities.py — Agent personality profiles for the thought-bubble visualizer.

Each agent has:
  archetype     : one-line role description
  description   : sentence about how they think
  color         : Rich / CSS color token
  <context>     : list of catchphrases chosen at runtime based on agent findings
"""
from __future__ import annotations

PERSONALITIES: dict[str, dict] = {

    # ------------------------------------------------------------------ #
    #  SENTINEL — cold rule engine that never raises a false alarm
    # ------------------------------------------------------------------ #
    "sentinel": {
        "archetype": "The Alarm System",
        "description": "Cold, terse — sees what the logs miss",
        "color": "cyan",
        "high_confidence": [
            "Pattern matched. No false alarm.",
            "Threshold crossed. This one's real.",
            "I don't cry wolf.",
            "The numbers don't lie.",
        ],
        "low_confidence": [
            "Something's off. I can't quantify it yet.",
            "Anomaly detected. Confidence still building.",
        ],
        "fallback": [
            "Signal incomplete. Flagging anyway.",
            "Partial data. Still raising the alarm.",
        ],
        "suspicious": [
            "Port sweep detected. Classic recon signature.",
            "Traffic spike. Someone's pushing hard.",
            "Failed connections. They're probing for weakness.",
            "Ports don't lie. This is deliberate.",
        ],
        "benign": [
            "Normal traffic. Nothing to escalate.",
            "Within baseline. Standing down.",
            "Noise, not signal. Logging and moving on.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  WHOIS — follows the ASN, follows the money
    # ------------------------------------------------------------------ #
    "whois": {
        "archetype": "The Street Investigator",
        "description": "Follows the money, reads the network registration",
        "color": "yellow",
        "high_confidence": [
            "Follow the ASN, follow the money.",
            "I've traced this ownership before. It leads nowhere good.",
            "The paperwork checks out — and that's exactly the problem.",
            "ARIN doesn't lie. I just read what it tells me.",
        ],
        "low_confidence": [
            "Registration details are thin. Could be clean, could be laundered.",
            "ASN is clean on paper. I'm not convinced yet.",
            "Ownership trail is murky. Need more to go on.",
        ],
        "fallback": [
            "RDAP timed out. Working blind on this one.",
            "Network registry isn't talking. I'll note the silence.",
            "No ownership data. That's suspicious in itself.",
        ],
        "suspicious": [
            "VPS hosting. Classic attacker infrastructure.",
            "Data center IP. Nobody benign runs exclusively out of here.",
            "Registered recently. Fresh sock puppet operation.",
            "Cloud provider — low barrier to entry, high attacker preference.",
        ],
        "benign": [
            "Legit org. ARIN agrees.",
            "Known provider. Clean registration trail.",
            "Nothing suspicious in the paperwork. Moving on.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  DNS — silent tracker, reads the digital footprints
    # ------------------------------------------------------------------ #
    "dns": {
        "archetype": "The Quiet Tracker",
        "description": "Follows digital footprints, speaks only in clues",
        "color": "blue",
        "high_confidence": [
            "The hostname tells a story.",
            "PTR record confirms what I suspected.",
            "I read the wire. This IP isn't hiding well.",
            "Reverse lookup doesn't lie.",
        ],
        "low_confidence": [
            "Reverse lookup incomplete. Watching.",
            "Hostname pattern ambiguous. Could go either way.",
            "Not enough DNS signal yet.",
        ],
        "fallback": [
            "No PTR record. They don't want to be found.",
            "DNS is silent. Deliberate or careless — neither is good.",
            "Lookup failed. The absence of data is data.",
        ],
        "suspicious": [
            "VPS hostname pattern. Attacker-controlled node.",
            "Hostname looks autogenerated. Throwaway infrastructure.",
            "Dynamic DNS. They're rotating this regularly.",
            "The hostname doesn't match what the WHOIS says. That's a tell.",
        ],
        "benign": [
            "Hostname matches a legitimate provider.",
            "PTR resolves cleanly. Consistent with stated ownership.",
            "DNS checks out. No anomalies.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  PORT INTEL — reads the attack playbook
    # ------------------------------------------------------------------ #
    "port_intel": {
        "archetype": "The Military Tactician",
        "description": "Speaks in MITRE codes, reads attack playbooks",
        "color": "red",
        "high_confidence": [
            "I've seen this port combination before.",
            "The playbook is clear. This isn't random scanning.",
            "T-code confirmed. I know exactly what they're after.",
            "Classic credential-access kit. Textbook.",
        ],
        "low_confidence": [
            "Mixed signals from the port data. Could be noise.",
            "Port profile is incomplete. Can't call the technique yet.",
            "Ambiguous target set. Not a clear objective.",
        ],
        "fallback": [
            "Port DB lookup failed. Operating on general knowledge.",
            "No entry in the database. Unusual port configuration.",
        ],
        "suspicious": [
            "22, 445, 3389 — that's a credential extraction kit.",
            "These ports don't appear together by accident.",
            "Classic lateral movement setup. They're planning the next step.",
            "Targeting RDP and SMB. Ransomware pre-positioning.",
        ],
        "benign": [
            "Standard web ports. Nothing tactical here.",
            "Port profile consistent with normal service exposure.",
            "80 and 443. Probably just a web client.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  REPUTATION — the bounty hunter with a database full of rap sheets
    # ------------------------------------------------------------------ #
    "reputation": {
        "archetype": "The Bounty Hunter",
        "description": "Trusts the score, reads the rap sheet",
        "color": "magenta",
        "high_confidence": [
            "23 priors. I don't need a spreadsheet to call this one.",
            "Score of 87/100 — practically wearing a name tag.",
            "This IP has a longer record than most of my active cases.",
            "Community already flagged this. I'm just confirming.",
        ],
        "low_confidence": [
            "Score is mid-range. Could be a first-timer or a professional.",
            "Not enough reports to call it conclusively.",
            "AbuseIPDB is on the fence. I'll defer to the others.",
        ],
        "fallback": [
            "AbuseIPDB isn't answering. Working the case without the database.",
            "API down. Going on prior knowledge only.",
            "No reputation data. That's not a clean bill of health.",
        ],
        "suspicious": [
            "High abuse score. This one's been busy.",
            "Multiple reporters. Someone else already flagged this.",
            "Recent activity. This isn't a cold case.",
            "Consistent abuse categories. Habitual offender.",
        ],
        "benign": [
            "Clean record. Zero reports.",
            "AbuseIPDB gives it a pass. I'll note it but I'm not convinced.",
            "No prior incidents. First-timer or legitimately clean.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  ORCHESTRATOR — war room commander, synthesizes the full picture
    # ------------------------------------------------------------------ #
    "orchestrator": {
        "archetype": "The War Room Commander",
        "description": "Synthesizes the battlefield intelligence, makes the call",
        "color": "white",
        "high_confidence": [
            "All reports in. Here's the verdict.",
            "Three sources, one conclusion. I'm calling it.",
            "The picture is clear. We move.",
            "No conflicting signals. Solid intel.",
        ],
        "low_confidence": [
            "Intelligence is mixed. Escalating to human review.",
            "Confidence below threshold. I won't gamble on this one.",
            "Partial picture. Human judgment required.",
        ],
        "fallback": [
            "Some agents went dark. Verdict adjusted for missing intel.",
            "Acting on what I have. Confidence is reduced.",
        ],
        "suspicious": [
            "Converging evidence. The threat is real.",
            "Every agent is pointing the same direction.",
            "Classification: malicious. Recommend action.",
            "Multiple attack indicators confirmed. No ambiguity.",
        ],
        "benign": [
            "Evidence points clean. Standing down.",
            "Agents agree — no threat. Logging and moving on.",
            "Low risk profile across all dimensions. Clear.",
        ],
    },

    # ------------------------------------------------------------------ #
    #  POLICY — the judge: rules are rules
    # ------------------------------------------------------------------ #
    "policy": {
        "archetype": "The Judge",
        "description": "Rules-based, final, and non-negotiable",
        "color": "green",
        "high_confidence": [
            "Policy is unambiguous. The verdict stands.",
            "No exceptions in the rulebook for this.",
            "The law is the law.",
            "Rules applied. Ruling is final.",
        ],
        "low_confidence": [
            "Edge case. Applying the closest matching rule.",
            "Policy guidance is imprecise here. Erring conservative.",
        ],
        "fallback": [
            "Action outside allowed set. Defaulting to safe path.",
            "Unknown action requested. Policy overrides to log_only.",
        ],
        "suspicious": [
            "Severity confirmed. Block is authorized.",
            "Human escalation required. I don't override the threshold.",
            "LLM recommendation overruled — severity too low to block.",
            "Protected IP — action suppressed by policy.",
        ],
        "benign": [
            "Action approved. All policy checks passed.",
            "Low severity. Log it and move on.",
            "No policy flags. Proceeding as recommended.",
        ],
    },
}
