worker_processes 1;

events {}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 'threat-lab victim\n';
            add_header Content-Type text/plain;
        }
    }
}
